config/routes.rb
Rails.application.routes.draw do
  resources :definitions do
    collection do
      get :search
    end
  end

  root 'definitions#index'

end

app/models/definition.rb
class Definition < ActiveRecord::Base
  validates :word, presence: true
  validates :meaning, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/definitions_controller.rb
class DefinitionsController < ApplicationController
  before_action :set_definition, only: [:show, :edit, :update, :destroy]

  # GET /definitions
  # GET /definitions.json
  def index
    @definitions = Definition.all

  end
  def search
    @search = params[:search]
    @definitions= Definition.where("word LIKE ?", "%#{@search}%")

    render :index
  end
  # GET /definitions/1
  # GET /definitions/1.json
  def show
  end

  # GET /definitions/new
  def new
    @definition = Definition.new
  end

  # GET /definitions/1/edit
  def edit
  end

  # POST /definitions
  # POST /definitions.json
  def create
    @definition = Definition.new(definition_params)

    respond_to do |format|
      if @definition.save
        format.html { redirect_to @definition, notice: 'Definition was successfully created.' }
        format.json { render :show, status: :created, location: @definition }
      else
        format.html { render :new }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /definitions/1
  # PATCH/PUT /definitions/1.json
  def update
    respond_to do |format|
      if @definition.update(definition_params)
        format.html { redirect_to @definition, notice: 'Definition was successfully updated.' }
        format.json { render :show, status: :ok, location: @definition }
      else
        format.html { render :edit }
        format.json { render json: @definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /definitions/1
  # DELETE /definitions/1.json
  def destroy
    @definition.destroy
    respond_to do |format|
      format.html { redirect_to definitions_url, notice: 'Definition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_definition
      @definition = Definition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def definition_params
      params.require(:definition).permit(:word, :meaning, :word_type, :sentence ,:search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/definitions_helper.rb
module DefinitionsHelper
end

app/views/definitions/_form.html.erb
<%= form_for(@definition) do |f| %>
  <% if @definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@definition.errors.count, "error") %> prohibited this definition from being saved:</h2>

      <ul>
      <% @definition.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :meaning %><br>
    <%= f.text_field :meaning %>
  </div>
  <div class="field">
    <%= f.label :word_type %><br>
    <%= f.select(:word_type,["noun", "verb", "adjective", "adverb"]) %>
  </div>
  <div class="field">
    <%= f.label :sentence %><br>
    <%= f.text_field :sentence %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/definitions/edit.html.erb
<h1>Editing Definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @definition %> |
<%= link_to 'Back', definitions_path %>

app/views/definitions/index.html.erb
<p id="notice"><%= notice %></p>
<link href='https://fonts.googleapis.com/css?family=Lato:300italic' rel='stylesheet' type='text/css'>

<h1>Out Of This World Jargon</h1>
<%= link_to 'New Alien Language? Add it here!', new_definition_path %>


<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Meaning</th>
      <th>Word Type</th>
      <th>Word Used in a Sentence</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @definitions.each do |definition| %>
      <tr>
        <td><%= definition.word %></td>
        <td><%= definition.meaning %></td>
        <td><%= definition.word_type %></td>
        <td><%= definition.sentence %></td>
        <td><%= link_to 'Show', definition %></td>
        <td><%= link_to 'Edit', edit_definition_path(definition) %></td>
        <td><%= link_to 'Destroy', definition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/definitions/new.html.erb
<h1>New Definition</h1>

<%= render 'form' %>

<%= link_to 'Back', definitions_path %>

app/views/definitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @definition.word %>
</p>

<p>
  <strong>Meaning:</strong>
  <%= @definition.meaning %>
</p>

<p>
  <strong>Word Type:</strong>
  <%= @definition.word_type %>
</p>
<p>
  <strong>Write a sentence using the word:</strong>
  <%= @definition.sentence %>
</p>

<%= link_to 'Edit', edit_definition_path(@definition) %> |
<%= link_to 'Back', definitions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsdictionary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= image_tag("logo.png",width: '90', height: '70') %>
    <div id="search">
      <%= form_tag(search_definitions_path,method: "get") do %>
          <%= text_field_tag :search %>
          <%= submit_tag "Search" %>
      <% end %>
    </div>
  </header>

<%= yield %>

</body>
</html>